version: '3.2'

services:
  db:
    image: postgres:12.0-alpine
    container_name: smart-door-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432

  web:
    container_name: smart-door-web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/opt/smart-door
    depends_on:
      - db

volumes:
  postgres_data:
