definitions:
  apperror.AppError:
    properties:
      details:
        items:
          type: integer
        type: array
      message:
        type: string
    type: object
  domain.Event:
    properties:
      direction:
        type: string
      event_time:
        type: string
      id:
        type: integer
      user_id:
        type: integer
    type: object
  domain.User:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      patronymic:
        type: string
      person_id:
        type: string
      phone:
        type: string
      position:
        type: string
      role:
        type: string
      updated_at:
        type: string
    type: object
  dto.CreateEvent:
    properties:
      direction:
        type: string
      event_time:
        type: string
      user_id:
        type: integer
    type: object
  dto.CreateUser:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      patronymic:
        type: string
      person_id:
        type: string
      position:
        type: string
    type: object
  dto.RecognizeUser:
    properties:
      direction:
        type: string
      event_time:
        type: string
      person_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/users:
    post:
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
        "418":
          description: I'm a teapot
      summary: Creating a regular user
      tags:
      - Users
  /api/v1/users/recognize:
    post:
      parameters:
      - description: event info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.RecognizeUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
        "418":
          description: I'm a teapot
      summary: Recognize user
      tags:
      - Users
swagger: "2.0"
